'use client';
import Link from 'next/link';

const features = [
  {
    icon: '🤖',
    title: '24/7 Doubt Destroyer',
    desc: 'Get instant answers to your doubts in Hinglish — like having a personal tutor always available.',
    color: '#6366f1',
  },
  {
    icon: '📝',
    title: 'One-Page Summaries',
    desc: 'AI converts 20-page chapters into quick revision notes. Perfect for last-minute prep.',
    color: '#8b5cf6',
  },
  {
    icon: '🎯',
    title: 'Mock Test Generator',
    desc: 'Instant 10-minute quizzes on any topic. Board-exam level questions generated by AI.',
    color: '#06b6d4',
  },
  {
    icon: '✅',
    title: 'Board Examiner Mode',
    desc: 'AI grades your handwritten answers exactly like a board examiner. Get marks + feedback.',
    color: '#f59e0b',
  },
  {
    icon: '📚',
    title: 'PYQ Archive',
    desc: 'Last 10 years of board questions categorized by chapter. Find patterns, score better.',
    color: '#10b981',
  },
  {
    icon: '🔥',
    title: 'Study Streaks & Leaderboard',
    desc: 'Compete with peers, maintain streaks, and earn points for consistent preparation.',
    color: '#ef4444',
  },
];

export default function Home() {
  return (
    <div>
      <div className="animated-bg"></div>
      
      {/* Hero Section */}
      <section style={{
        padding: '120px 24px 100px',
        maxWidth: '1200px',
        margin: '0 auto',
        display: 'flex',
        alignItems: 'center',
        gap: '60px',
        flexWrap: 'wrap',
      }}>
        <div className="animate-fade-in" style={{ flex: '1 1 500px' }}>
          <div style={{
            display: 'inline-block',
            padding: '8px 20px',
            borderRadius: '50px',
            background: 'rgba(99, 102, 241, 0.15)',
            border: '1px solid rgba(99, 102, 241, 0.3)',
            fontSize: '14px',
            color: '#a5b4fc',
            marginBottom: '28px',
            fontWeight: 600,
          }}>
            🚀 Powered by Google Gemini 1.5 Flash
          </div>
          <h1 style={{
            fontSize: 'clamp(40px, 6vw, 72px)',
            fontWeight: 900,
            lineHeight: 1.05,
            marginBottom: '24px',
            letterSpacing: '-2px',
          }}>
            Master Your <br />
            Boards <span className="gradient-text">With AI</span>
          </h1>
          <p style={{
            fontSize: '19px',
            color: 'rgba(255,255,255,0.6)',
            maxWidth: '540px',
            marginBottom: '40px',
            lineHeight: 1.6,
          }}>
            The ultimate AI study companion for Class 10th & 12th. Get instant Hinglish doubts, chapter summaries, 3D flashcards, and automated grading.
          </p>
          <div style={{ display: 'flex', gap: '16px', flexWrap: 'wrap' }}>
            <Link href="/register">
              <button className="btn-primary" style={{ fontSize: '17px', padding: '16px 40px' }}>
                Join 10,000+ Students →
              </button>
            </Link>
          </div>
          
          <div style={{ marginTop: '48px', display: 'flex', gap: '24px', alignItems: 'center' }}>
             <div style={{ display: 'flex', marginLeft: '10px' }}>
                {[1,2,3,4].map(i => (
                  <div key={i} style={{ 
                    width: '36px', height: '36px', borderRadius: '50%', background: '#1a1a2e', 
                    border: '2px solid #0a0a1a', marginLeft: '-10px', 
                    display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '18px'
                  }}>
                    {['👨‍🎓', '👩‍🎓', '🧑‍🎓', '👩‍💻'][i-1]}
                  </div>
                ))}
             </div>
             <div style={{ fontSize: '14px', color: 'rgba(255,255,255,0.4)' }}>
                <span style={{ color: '#10b981', fontWeight: 700 }}>● 274 Students</span> studying right now
             </div>
          </div>
        </div>

        <div className="animate-fade-in" style={{ 
          flex: '1 1 400px', 
          position: 'relative', 
          animationDelay: '0.2s', 
          animationFillMode: 'backwards' 
        }}>
          <div style={{
            position: 'absolute',
            top: '50%',
            left: '50%',
            transform: 'translate(-50%, -50%)',
            width: '120%',
            height: '120%',
            background: 'radial-gradient(circle, rgba(99, 102, 241, 0.2) 0%, transparent 70%)',
            zIndex: -1,
          }}></div>
          <img 
            src="/hero.png" 
            alt="AI Tutor Illustration" 
            style={{
              width: '100%',
              borderRadius: '24px',
              boxShadow: '0 20px 80px rgba(0,0,0,0.5), 0 0 40px rgba(99, 102, 241, 0.2)',
              border: '1px solid rgba(255,255,255,0.1)',
            }}
          />
        </div>
      </section>

      {/* Features Heading */}
      <div style={{ textAlign: 'center', marginBottom: '60px' }}>
        <h2 style={{ fontSize: 'clamp(32px, 4vw, 48px)', fontWeight: 800 }}>Powerful <span className="gradient-text">Core Features</span></h2>
        <p style={{ color: 'rgba(255,255,255,0.4)', marginTop: '10px' }}>Built for Indian students by experts in AI and Education.</p>
      </div>

      {/* Features Grid */}
      <section style={{
        padding: '0 24px 120px',
        maxWidth: '1200px',
        margin: '0 auto',
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(360px, 1fr))',
        gap: '24px',
      }}>
        {features.map((f, i) => (
          <div
            key={i}
            className="glass-card animate-fade-in"
            style={{
              padding: '40px',
              animationDelay: `${i * 0.1}s`,
              animationFillMode: 'backwards',
              display: 'flex',
              flexDirection: 'column',
              gap: '20px',
            }}
          >
            <div style={{
              width: '64px',
              height: '64px',
              borderRadius: '18px',
              background: `linear-gradient(135deg, ${f.color}22, ${f.color}44)`,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontSize: '32px',
              boxShadow: `0 8px 20px ${f.color}15`,
            }}>
              {f.icon}
            </div>
            <div>
              <h3 style={{ fontSize: '20px', fontWeight: 800, marginBottom: '12px' }}>{f.title}</h3>
              <p style={{ color: 'rgba(255,255,255,0.5)', lineHeight: 1.6, fontSize: '15px' }}>{f.desc}</p>
            </div>
            <div style={{ marginTop: 'auto', paddingTop: '10px' }}>
               <Link href="/register" style={{ fontSize: '13px', color: f.color, fontWeight: 700, textDecoration: 'none' }}>
                  Explore Feature →
               </Link>
            </div>
          </div>
        ))}
      </section>

      {/* Footer */}
      <footer style={{
        textAlign: 'center',
        padding: '80px 24px 40px',
        borderTop: '1px solid rgba(255,255,255,0.05)',
        color: 'rgba(255,255,255,0.25)',
        fontSize: '14px',
      }}>
        <div style={{ marginBottom: '20px', fontSize: '24px' }}>🎓</div>
        © 2026 BoardPrep AI — Built for Indian Students 🇮🇳
      </footer>
    </div>
  );
}
