'use client';
import Link from 'next/link';

const features = [
  {
    icon: '🤖',
    title: '24/7 Doubt Destroyer',
    desc: 'Get instant answers to your doubts in Hinglish — like having a personal tutor always available.',
    color: '#6366f1',
  },
  {
    icon: '📝',
    title: 'One-Page Summaries',
    desc: 'AI converts 20-page chapters into quick revision notes. Perfect for last-minute prep.',
    color: '#8b5cf6',
  },
  {
    icon: '🎯',
    title: 'Mock Test Generator',
    desc: 'Instant 10-minute quizzes on any topic. Board-exam level questions generated by AI.',
    color: '#06b6d4',
  },
  {
    icon: '✅',
    title: 'Board Examiner Mode',
    desc: 'AI grades your handwritten answers exactly like a board examiner. Get marks + feedback.',
    color: '#f59e0b',
  },
  {
    icon: '📚',
    title: 'PYQ Archive',
    desc: 'Last 10 years of board questions categorized by chapter. Find patterns, score better.',
    color: '#10b981',
  },
  {
    icon: '🔥',
    title: 'Study Streaks & Leaderboard',
    desc: 'Compete with peers, maintain streaks, and earn points for consistent preparation.',
    color: '#ef4444',
  },
];

export default function Home() {
  return (
    <div>
      {/* Hero Section */}
      <section style={{
        padding: '100px 24px 80px',
        textAlign: 'center',
        maxWidth: '900px',
        margin: '0 auto',
      }}>
        <div className="animate-fade-in">
          <div style={{
            display: 'inline-block',
            padding: '8px 20px',
            borderRadius: '50px',
            background: 'rgba(99, 102, 241, 0.15)',
            border: '1px solid rgba(99, 102, 241, 0.3)',
            fontSize: '14px',
            color: '#a5b4fc',
            marginBottom: '28px',
          }}>
            🚀 Powered by Google Gemini AI
          </div>
          <h1 style={{
            fontSize: 'clamp(36px, 5vw, 64px)',
            fontWeight: 900,
            lineHeight: 1.1,
            marginBottom: '24px',
            letterSpacing: '-1.5px',
          }}>
            Crack Your Board Exams <br />
            <span className="gradient-text">With AI Superpowers</span>
          </h1>
          <p style={{
            fontSize: '18px',
            color: 'rgba(255,255,255,0.55)',
            maxWidth: '600px',
            margin: '0 auto 40px',
            lineHeight: 1.7,
          }}>
            The smartest study companion for Class 10th & 12th students. AI-powered doubts, summaries,
            quizzes, and grading — all in one place.
          </p>
          <div style={{ display: 'flex', gap: '14px', justifyContent: 'center' }}>
            <Link href="/register">
              <button className="btn-primary" style={{ fontSize: '16px', padding: '14px 36px' }}>
                Start Free Prep →
              </button>
            </Link>
            <Link href="/login">
              <button className="btn-secondary" style={{ fontSize: '16px', padding: '14px 36px' }}>
                Login
              </button>
            </Link>
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section style={{
        padding: '20px 24px 100px',
        maxWidth: '1200px',
        margin: '0 auto',
      }}>
        <h2 style={{
          textAlign: 'center',
          fontSize: '32px',
          fontWeight: 800,
          marginBottom: '48px',
          letterSpacing: '-0.5px',
        }}>
          Everything You Need to <span className="gradient-text">Score Big</span>
        </h2>
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(340px, 1fr))',
          gap: '20px',
        }}>
          {features.map((f, i) => (
            <div
              key={i}
              className="glass-card animate-fade-in"
              style={{
                padding: '32px',
                animationDelay: `${i * 0.1}s`,
                animationFillMode: 'backwards',
              }}
            >
              <div style={{
                width: '52px',
                height: '52px',
                borderRadius: '14px',
                background: `${f.color}22`,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: '26px',
                marginBottom: '18px',
              }}>
                {f.icon}
              </div>
              <h3 style={{
                fontSize: '19px',
                fontWeight: 700,
                marginBottom: '10px',
              }}>
                {f.title}
              </h3>
              <p style={{
                color: 'rgba(255,255,255,0.5)',
                fontSize: '15px',
                lineHeight: 1.6,
              }}>
                {f.desc}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* Stats Section */}
      <section style={{
        padding: '60px 24px',
        maxWidth: '900px',
        margin: '0 auto',
        textAlign: 'center',
      }}>
        <div className="glass-card" style={{
          padding: '48px 32px',
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
          gap: '32px',
        }}>
          {[
            { num: '10K+', label: 'Active Students' },
            { num: '50K+', label: 'Doubts Solved' },
            { num: '95%', label: 'Satisfaction' },
            { num: '100+', label: 'Chapters Covered' },
          ].map((s, i) => (
            <div key={i}>
              <div className="gradient-text" style={{
                fontSize: '36px',
                fontWeight: 900,
              }}>
                {s.num}
              </div>
              <div style={{
                color: 'rgba(255,255,255,0.45)',
                fontSize: '14px',
                marginTop: '4px',
              }}>
                {s.label}
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer style={{
        textAlign: 'center',
        padding: '40px 24px',
        color: 'rgba(255,255,255,0.3)',
        fontSize: '14px',
      }}>
        © 2026 BoardPrep AI — Built with ❤️ for Indian Students
      </footer>
    </div>
  );
}
