// frontend/app/lib/notesData.js
// Subject → Units mapping for Class 10 & 12

export const notesData = {
    10: {
        Physics: {
            icon: "⚡",
            color: "#6366f1",
            units: [
                "Light — Reflection and Refraction",
                "Human Eye and the Colourful World",
                "Electricity",
                "Magnetic Effects of Electric Current",
                "Sources of Energy",
            ],
        },
        Chemistry: {
            icon: "🧪",
            color: "#10b981",
            units: [
                "Chemical Reactions and Equations",
                "Acids, Bases and Salts",
                "Metals and Non-metals",
                "Carbon and its Compounds",
                "Periodic Classification of Elements",
            ],
        },
        Biology: {
            icon: "🌿",
            color: "#f59e0b",
            units: [
                "Life Processes",
                "Control and Coordination",
                "How do Organisms Reproduce?",
                "Heredity and Evolution",
                "Our Environment",
                "Sustainable Management of Natural Resources",
            ],
        },
        Mathematics: {
            icon: "📐",
            color: "#ec4899",
            units: [
                "Real Numbers",
                "Polynomials",
                "Pair of Linear Equations in Two Variables",
                "Quadratic Equations",
                "Arithmetic Progressions",
                "Triangles",
                "Coordinate Geometry",
                "Introduction to Trigonometry",
                "Circles",
                "Areas Related to Circles",
                "Surface Areas and Volumes",
                "Statistics",
                "Probability",
            ],
        },
        English: {
            icon: "📖",
            color: "#8b5cf6",
            units: [
                "A Letter to God",
                "Nelson Mandela — Long Walk to Freedom",
                "Two Stories about Flying",
                "From the Diary of Anne Frank",
                "The Hundred Dresses",
                "Glimpses of India",
                "Mijbil the Otter",
                "Madam Rides the Bus",
                "The Sermon at Benares",
                "The Proposal",
                "Grammar & Writing Skills",
            ],
        },
    },
    12: {
        Physics: {
            icon: "⚡",
            color: "#6366f1",
            units: [
                "Electric Charges and Fields",
                "Electrostatic Potential and Capacitance",
                "Current Electricity",
                "Moving Charges and Magnetism",
                "Magnetism and Matter",
                "Electromagnetic Induction",
                "Alternating Current",
                "Electromagnetic Waves",
                "Ray Optics and Optical Instruments",
                "Wave Optics",
                "Dual Nature of Radiation and Matter",
                "Atoms",
                "Nuclei",
                "Semiconductor Electronics",
            ],
        },
        Chemistry: {
            icon: "🧪",
            color: "#10b981",
            units: [
                "The Solid State",
                "Solutions",
                "Electrochemistry",
                "Chemical Kinetics",
                "Surface Chemistry",
                "General Principles and Processes of Isolation of Elements",
                "The p-Block Elements",
                "The d- and f-Block Elements",
                "Coordination Compounds",
                "Haloalkanes and Haloarenes",
                "Alcohols, Phenols and Ethers",
                "Aldehydes, Ketones and Carboxylic Acids",
                "Amines",
                "Biomolecules",
            ],
        },
        Biology: {
            icon: "🌿",
            color: "#f59e0b",
            units: [
                "Reproduction in Organisms",
                "Sexual Reproduction in Flowering Plants",
                "Human Reproduction",
                "Reproductive Health",
                "Principles of Inheritance and Variation",
                "Molecular Basis of Inheritance",
                "Evolution",
                "Human Health and Disease",
                "Strategies for Enhancement in Food Production",
                "Microbes in Human Welfare",
                "Biotechnology — Principles and Processes",
                "Biotechnology and its Applications",
                "Organisms and Populations",
                "Ecosystem",
                "Biodiversity and Conservation",
            ],
        },
        Mathematics: {
            icon: "📐",
            color: "#ec4899",
            units: [
                "Relations and Functions",
                "Inverse Trigonometric Functions",
                "Matrices",
                "Determinants",
                "Continuity and Differentiability",
                "Application of Derivatives",
                "Integrals",
                "Application of Integrals",
                "Differential Equations",
                "Vector Algebra",
                "Three Dimensional Geometry",
                "Linear Programming",
                "Probability",
            ],
        },
        English: {
            icon: "📖",
            color: "#8b5cf6",
            units: [
                "The Last Lesson",
                "Lost Spring",
                "Deep Water",
                "The Rattrap",
                "Indigo",
                "Poets and Pancakes",
                "The Interview",
                "Going Places",
                "My Mother at Sixty-six",
                "An Elementary School Classroom in a Slum",
                "Keeping Quiet",
                "A Thing of Beauty",
                "A Roadside Stand",
                "Aunt Jennifer's Tigers",
                "Grammar & Writing Skills",
            ],
        },
    },
};
